apply plugin: 'java-library'

dependencies {
    api project(":client")
    api libs.retrofit
    implementation libs.retrofitRxJava2
    implementation libs.retrofitJackson
    implementation libs.victoolsJsonSchemaGenerator
    implementation libs.victoolsJsonSchemaJackson
    implementation libs.javaxValidationApi

    testImplementation(platform(libs.junitBom))
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation libs.retrofitMock
}

compileJava {
    sourceCompatibility = '1.8'
    targetCompatibility = '1.8'
}

test {
    useJUnitPlatform()
}
