name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}
  # OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # for setup launchable command
      - uses: actions/setup-python@v5
      - name: Install launchable CLI
        run: |
          pip install launchable
      - name: Set up JDK 1.11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: Record commits and build
        run: 'launchable record build --name "$GITHUB_RUN_ID" --source .'
      - name: Test
        run: ./gradlew test --stacktrace
      - name: Record
        run: launchable record tests gradle **/build/test-results/test/*.xml
        if: always()

